### ISSUE TITLE
Convert numpy ndarray type to HPy

### ISSUE THREAD

**Issue by antocuni** [hpyproject/hpy#138]
As a first step towards #137, convert ndarray to an HPy type, defined using HPyType_FromSpec.

Note that this doesn't require converting any of its methods and slots, as they can be used unchanged through HPy's legacy slots feature.

**Comment by CorruptedArk** [comment]
Hi @antocuni, I'm interested in resolving this issue and I have a some questions in regard to it. I read the porting guide so I have a rough idea of what you're looking for, but I'm not exactly sure about how you want it implemented. What should be the name of the file/files (depending on whether the class should be split into .c and .h) and what directory should the class be placed in once it is written?

**Comment by antocuni** [comment]
@CorruptedArk thank you for your interest! I think you should coordinate with @rlamy who has already started the task in [this repo](https://github.com/hpyproject/numpy-hpy)

**Comment by rlamy** [comment]
I think it's done now, see https://github.com/hpyproject/numpy-hpy/commits/hpy

**Comment by rgommers** [comment]
Nice. The diff in https://github.com/numpy/numpy/compare/master...hpyproject:hpy looks good, somehow smaller than I had expected (not knowing much about HPy).

**Comment by rlamy** [comment]
@rgommers Note that it's a bare-bones conversion. Almost nothing actually uses HPy in the current state of the code. However, it does allow slots and methods of ndarray to be incrementally converted.
