### ISSUE TITLE
hpy.universal leak handles and it's unnecessary slow

### ISSUE THREAD

**Issue by antocuni** [hpyproject/hpy#155]
The title mentions two different problems but I am grouping them in the same issue since I think they can be solved together.
I am already working on a fix in PR #142 but I thought it was useful to report my findings here, for the future.

First problem: consider `ctx_CallRealFunctionFromTrampoline`:
https://github.com/hpyproject/hpy/blob/fdc6047e6db755ecaeded1f805b91823eb11f08d/hpy/universal/src/ctx_meth.c#L6-L15

in CPython-ABI mode this is not a problem because `_py2h` and `_h2py` are just no-op casts, but in in universal mode, `_py2h` allocates new handles which are never freed:
https://github.com/hpyproject/hpy/blob/fdc6047e6db755ecaeded1f805b91823eb11f08d/hpy/universal/src/handles.c#L137-L152

The proper solution is something like this:
```c
    switch (sig) {
    case HPyFunc_NOARGS: {
        HPyFunc_noargs f = (HPyFunc_noargs)func;
        _HPyFunc_args_NOARGS *a = (_HPyFunc_args_NOARGS*)args;
        HPy h0 = _py2h(a->self);
        a->result = _h2py(f(ctx, h0));
        _hclose_nodecref(h0);
        return;
    }
```

However, there is a better solution: the second problem is that the current implementation of handles is unnecessarily slow. I tried the ujson and piconumpy benchmarks:
- ujson: the universal ABI is ~15% slower than the CPython ABI
- piconumpy: the universal ABI is ~35% slower than the CPython ABI

In PR #142 I am experimenting with a different approach for `hpy.universal`. In particular, `_py2h` and `_h2py` are implemented like this:
```c
// The main reason for +1/-1 is to make sure that if people casts HPy to
// PyObject* directly, things explode.

static inline HPy _py2h(PyObject *obj) {
    if (obj == NULL)
        return HPy_NULL;
    return (HPy){(HPy_ssize_t)(obj + 1)};
}

static inline PyObject *_h2py(HPy h) {
    if HPy_IsNull(h)
        return NULL;
    return (PyObject *)(h._i - 1);
}
```

So, they are basically no-op casts again, and the benchmarks are much faster:
- ujson: the universal ABI is ~0.9% slower than the CPython ABI
- piconumpy: the universal ABI is ~6% slower than the CPython ABI

**Historical note**: why do we represent hpy.universal handles as indexes in a list? The original ideas was to support the debug mode, so that we could easily store extra debugging infos for each handles.

The idea that I am trying in PR #142 is different, i.e. to wrap a generic universal ctx into a debug ctx: so, debug handles are wrapper around generic opaque universal handles and the extra infos can be attached directly on the wrappers. Moreover, by doing that we pay the overhead of "heavy" handles only for the modules for which the debug mode is enabled.

**EDIT**: fixed the PR number

**Comment by fangerer** [comment]
Could it be that PR https://github.com/hpyproject/hpy/pull/43 is the wrong reference?

**Comment by antocuni** [comment]
> Could it be that PR #43 is the wrong reference?

yes, sorry! I fixed it with the correct link
