### ISSUE TITLE
Don't use Variable Length Arrays (VLA)

### ISSUE THREAD

**Issue by antocuni** [hpyproject/hpy#157]
VLA are a feature of C99 but they are optional so not all compilers use it.
At first, we used `alloca` to allocate arrays on the stack, then we introduced VLA in #76 , but this causes problems on windows, see #125 .

We should revert #76 .

**Comment by mattip** [comment]
I think this was mistakenly closed by a random comment in the commit message

**Comment by antocuni** [comment]
indeed... bad github! :man_facepalming: 
Reopening

**Comment by mattip** [comment]
It seems the interface to `ctx_CallRealFunctionFromTrampoline` does not allow for the call to fail since it returns `void`. What should happen if the stack allocation of `h_args` fails?

**Comment by antocuni** [comment]
it "returns" a value by setting `a->result` (this is needed because the return type might be different). So you should set `a->result` to the appropriate error value depending on the signature
