### ISSUE TITLE
Make it possible to put HPyType_Spec in HPyModuleDef.defines

### ISSUE THREAD

**Issue by antocuni** [hpyproject/hpy#158]
This is an idea which just came to my mind, let me write it down not to forget.
To create a type, we currently need to define an `HPyType_Spec` and then manually call `HPyType_FromSpec` in the module init, as you do on CPython.
However, for the vast majority of cases this is unnecessarily complicate. Let's support something like this:
```c
HPyType_Spec PointType_spec = { ... };
HPyDef_TYPE(Point_def, "Point", PointType_spec);

static HPyDef *module_defines[] = {
    &Point_def,
    NULL
};

static HPyModuleDef moduledef = {
    HPyModuleDef_HEAD_INIT,
    .m_name = "foo",
    .defines = module_defines
};
```

The semantics would be to call `HPyType_FromSpec` and put the result inside the module dictionary, of course

**Comment by hodgestar** [comment]
I like this idea & I suggested something similar myself in IRC.

The upsides: removes the only non-declarative part of defining types in modules; provides one obvious way to set up a type; helps people avoid accidentally doing slightly odd things during type setup.

Downsides: adds a layer of abstraction; makes it a bit harder to customize type setup; I'm not sure how many types will need to doing something different during type setup.

**Comment by antocuni** [comment]
> I like this idea & I suggested something similar myself in IRC.

uh, maybe I read it on IRC and that's why it came to my mind: sorry for the missing attribution 😅.
OTOH, no cookie for you because you didn't open an issue first 😛
 
> The upsides: removes the only non-declarative part of defining types in modules; provides one obvious way to set up a type; helps people avoid accidentally doing slightly odd things during type setup.
> 
> Downsides: adds a layer of abstraction; makes it a bit harder to customize type setup; I'm not sure how many types will need to doing something different during type setup.

To be clear, I am not proposing to kill `HPyType_FromSpec`: it will still be possible to call it manually, if you want.

Also, note that maybe `HPyDef_TYPE` is not needed. We could write directly this:
```c
HPyDef PointTypeDef = {
    .kind = HPyDef_Kind_TypeSpec,
    .typespec = {
        .name = "foo",
        .defines = ...
    }
};
```

**Comment by hodgestar** [comment]
I started implementing this in https://github.com/hpyproject/hpy/pull/173, but passing a base type or metaclass requires access to the handle for that type, which won't be available statically. This made me wonder whether implementing this is a good idea? Perhaps there is something we can do instead?

**Comment by hodgestar** [comment]
I'm closing this and merging #180 which adds `HPyHelpers_AddType` as the eventual solution.
