### ISSUE TITLE
Rename HPy_Cast and HPy_CastLegacy.

### ISSUE THREAD

**Issue by hodgestar** [hpyproject/hpy#162]
The "cast" in `HPy_Cast` and `HPy_CastLegacy` suggest that these functions are merely type casts, when in fact they map an HPy handle to the custom type data associated with it.

It would be good to have a more accurate name. The leading contender is currently `HPy_AsStruct`.

When we rename this API methods, we should also rename the macro `HPy_CUSTOM_CAST`.

**Comment by antocuni** [comment]
For more context, the intended usage is the following:
```c
typedef struct {
    int x;
    int y;
} PointObject;

void foo(HPyContext ctx, HPy h) {
    PointObject *p = (PointObject*)HPy_AsStruct(ctx, h);
}
```

Random ideas for a new name:
- `HPy_AsStruct`
- `HPy_AsStructPtr`
- `HPy_Struct`
- `HPy_Ptr`
- `HPy_CPtr`
- `HPy_Layout`
- `HPy_CLayout`

I vote for `HPy_AsStruct`, but wanted to provide some alternatives to see whether someone comes up with a better idea.

**Comment by hodgestar** [comment]
I'm quite liking `HPy_CPtr`.

**Comment by fangerer** [comment]
:+1: for `HPy_AsStruct`

**Comment by hodgestar** [comment]
`HPy_AsStruct` and `HPy_AsStructLegacy` appear to have been the winning contenders here, on IRC and in the February dev call, so I've implement the name changes in #156.
