### ISSUE TITLE
Use function pointers (and not `void *`) for pointers to functions.

### ISSUE THREAD

**Issue by hodgestar** [hpyproject/hpy#174]
The CPython API uses `void *` for function pointers. However, in strict standard C, these are not the same things. If would be nice to resolve this issue in HPy.

Practical considerations:

* All the compilers we currently run integration tests against (gcc, clang, soon MSC) are fine with the difference.
* On some architectures data and instruction pointers are not even the same since.
* This also creates difficulties for Rust and WebAssembly, where the distinction between data and instruction pointers can be important.

See https://github.com/encukou/abi3/issues/14 for the same issue on CPython.

See #23 for an initial attempt at making this change in HPy.

**Comment by fangerer** [comment]
@qunaibit I think you already fixed that issue, right? Do you think we can close it?

**Comment by qunaibit** [comment]
Yes

**Comment by fangerer** [comment]
cool, thank you
