### ISSUE TITLE
HPyBytes_AsString should return const char*

### ISSUE THREAD

**Issue by antocuni** [hpyproject/hpy#183]
Currently we have:
```c
char* HPyBytes_AsString(HPyContext *ctx, HPy h);
char* HPyBytes_AS_STRING(HPyContext *ctx, HPy h);
```
these two functions were quickly added by me because I needed them for ujson. They return `char *` to match CPython's signature, but I think they should return `const char*` instead.
The reason why CPython's returns `char*` is this note in the docs:

> [...] The data must not be modified in any way, unless the object was just created using PyBytes_FromStringAndSize(NULL, size)

But I don't think we want to support this use case. Instead, we should introduce StringBuilders (see #181 ).

Moreover, this will be consistent with e.g. `[H]PyUnicode_AsUTF8`: it used to return `char*`, but since CPython 3.7 it returns `const char*`

Another question is whether we want to keep the `AS_STRING` version at all, and all the similar UPPERCASE macros. Ideally not, but on CPython they might be slightly faster, so we need proper benchmarks to make an proper decision.

**Comment by fangerer** [comment]
@hodgestar: Agreed. We already defined that and implemented exactly that check for `HPyUnicode_AsUTF8AndSize` (see function https://github.com/hpyproject/hpy/blob/8b33bd091edd1a40a00e16af5a0ada148cf5788a/hpy/debug/src/debug_ctx.c#L122). The infrastructure to do so is already there, so it shouldn't a problem to do the same for `HPyBytes_AsString`.
