### ISSUE TITLE
Refactor HPyModuleDef names

### ISSUE THREAD

**Issue by antocuni** [hpyproject/hpy#189]
https://github.com/hpyproject/hpy/blob/cc98cac7f623572c4b0096c1767d738b57b4beae/hpy/devel/include/common/hpymodule.h#L7-L16

at the beginning, we had to introduce `dummy` because in CPython mode, `HPyModuleDef` was a typedef to `PyModuleDef`. Nowadays, we use our own `HPyModuleDef` even in CPython mode, so we should kill this historical leftover.

Moreover, we should consider to remove the `m_` prefix in front of fields. We don't use these kind of prefixes anywhere else AFAIK

**Comment by hodgestar** [comment]
Things might get a bit more complicated:

`PyModuleDef` is sort of a Python type -- it has a `PyObject_HEAD and is returned as a `PyObject` by `PyModuleDef_Init`.  Of course one also creates instances of the struct directly.  Maybe this means that HPyModuleDef should become an actual type, or that there should be a separate type (maybe `HPyModuleDefObject` ?) that is returned by `HPyModuleDef_Init`.

**Comment by antocuni** [comment]
> `PyModuleDef` is sort of a Python type

yes but I don't think it's relevant here. In HPy, the only thing that you can do with an `HPyModuleDef` is to call `HPyModule_Create`: the actual `PyMethodDef` is created under the hood. Look at the code below, the `PyModule_HEAD_INIT` part is memcopied from `empty_moduledef`, and `dummy` is completely ignored:

https://github.com/hpyproject/hpy/blob/459758683e764a142ae82e9973c1f0730f651eaa/hpy/devel/src/runtime/ctx_module.c#L10-L30
