### ISSUE TITLE
error: piconumpy/_piconumpy_hpy.py already exists! Please delete.

### ISSUE THREAD

**Issue by paugier** [hpyproject/hpy#209]
I'm coming back to try piconumpy with newer hpy. 

It does not compile with hpy 0.0.2, so I tried with hpy d5c8442b.

With CPython, I get this error:

```
pierre@gre ~/Dev/piconumpy hpy-bench0 $ python setup.py --hpy-abi=universal develop                                                                                                                                
running develop
running egg_info
writing piconumpy.egg-info/PKG-INFO
writing dependency_links to piconumpy.egg-info/dependency_links.txt
writing requirements to piconumpy.egg-info/requires.txt
writing top-level names to piconumpy.egg-info/top_level.txt
writing manifest file 'piconumpy.egg-info/SOURCES.txt'
running build_ext
writing hpy universal stub loader for piconumpy._piconumpy_hpy to build/lib.linux-x86_64-3.8/piconumpy/_piconumpy_hpy.py
writing hpy universal stub loader for piconumpy._piconumpy_hpy to build/lib.linux-x86_64-3.8/piconumpy/_piconumpy_hpy.py
copying build/lib.linux-x86_64-3.8/piconumpy/_piconumpy_cpython_capi.cpython-38-x86_64-linux-gnu.so -> piconumpy
copying build/lib.linux-x86_64-3.8/piconumpy/_piconumpy_cython.cpython-38-x86_64-linux-gnu.so -> piconumpy
copying build/lib.linux-x86_64-3.8/piconumpy/_piconumpy_hpy.hpy.so -> piconumpy
writing hpy universal stub loader for piconumpy._piconumpy_hpy to piconumpy/_piconumpy_hpy.py
copying build/lib.linux-x86_64-3.8/piconumpy/_piconumpy_hpy.hpy.so -> piconumpy
writing hpy universal stub loader for piconumpy._piconumpy_hpy to piconumpy/_piconumpy_hpy.py
error: piconumpy/_piconumpy_hpy.py already exists! Please delete.
```

However, the extension is built and installed. It's only a problem with the stub file, which indeed has been created.

I'm not loving this idea of stub Python files, especially with `python setup.py develop` or `pip install -e .`. IMHO, it's not a good idea to add Python files in Python projects, for which Python files are the source files. How are we suppose to tell git/hg that these stub files should be ignored ?

**Comment by hodgestar** [comment]
@paugier The stub files are a temporary solution for CPython which cannot natively load universal extensions. We're open to better ideas, and we plan to ask CPython for explicit support or a better suggestion of how to proceed.

Regarding this specific issue: In the latest HPy, the stub files are overwritten instead of failing. Can I help get piconumpy working on the latest HPy somehow?

**Comment by paugier** [comment]
Oups, my bad. I tried to use hpy release/0.0.2 and I wasn't able to compile piconumpy. But with master, it works and indeed there is no problem with the stub file ! Sorry for this wrong issue. Thanks @hodgestar for your reply.

The only bad thing now is that PyPy still uses a quite outdated hpy version.

```
$ pypy --version                                                   
Python 3.7.10 (2c69b6ee2c0c, May 01 2021, 01:00:15)
[PyPy 7.3.6-alpha0 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]

$ pypy -c "import hpy.universal as u; print(u.get_version())"      
('0.1.dev959+geb07982', 'eb07982')
```

eb07982 corresponds to 0.0.1, which is not compatible with the most recent piconumpy. I guess I need to wait for hpy 0.0.2 and a version of PyPy working with hpy 0.0.2.

**Comment by hodgestar** [comment]
Support for HPy 0.0.2 is being added to PyPy is this branch -- https://foss.heptapod.net/pypy/pypy/-/commits/branch/hpy-0.0.2. Unfortunately 2021 hit a couple of the HPy team hard, so it didn't get everyone's full attention for a few weeks, but it is getting back on track now.
