### ISSUE TITLE
The default hpy_abi on PyPy is 'cpython'

### ISSUE THREAD

**Issue by antocuni** [hpyproject/hpy#217]
As the title says, if you try to `setup.py build` an hpy extension on PyPy, it implicitly uses `--hpy-abi=cpython`.

I think that by default, it should use `cpython` on CPython and `universal` on PyPy.

I don't know what is the best default for GraalPython: @fangerer, @timfel, what do you think?

**Comment by fangerer** [comment]
Definitively `universal` because that removes a lot of overhead.

**Comment by antocuni** [comment]
> Definitively `universal` because that removes a lot of overhead.

ok. My question was mainly if you preferred `universal` or some graalpython-specific ABI.

+1 for `universal`

**Comment by fangerer** [comment]
I do also prefer `universal`; so 👍 for it
