### ISSUE TITLE
piconumpy: error: ‘result’ may be used uninitialized in this function

### ISSUE THREAD

**Issue by paugier** [hpyproject/hpy#219]
I can't compile hpyproject/piconumpy (branch hpy). I get:

```
piconumpy/_piconumpy_hpy.c: In function ‘zeros_impl’:
piconumpy/_piconumpy_hpy.c:234:13: error: ‘result’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  234 |       result->data[i] = 0;
      |       ~~~~~~^~~~~~
compilation terminated due to -Wfatal-errors.
```

I don't understand why I get this warning which is turned into an error because of the flag `-Werror`. I can compile by removing this flag but it would be better not to get these warnings.

This is on Ubuntu 20.04 with gcc 9.3.0.

I post this here because there is no issue tracker for hpyproject/piconumpy.

**Comment by mwalkiewicz** [comment]
I've looked into piconumpys code and you should assign NULL to result pointer when declaring it. The compiler can't know that it'll have some value assigned when you pass a pointer to it as a parameter to another function few lines above the warning line.

**Comment by paugier** [comment]
Yes, it works (https://github.com/hpyproject/piconumpy/pull/3/commits/b46edf455b6ceb855d84068dc1b5827952728bfc)! Thanks a lot @mwalkiewicz!
