### ISSUE TITLE
Improve our release process

### ISSUE THREAD

**Issue by antocuni** [hpyproject/hpy#223]
Currently we don't have any automated release process: hpy releases (such as the upcoming 0.0.2) are manually uploaded using `twine`, and we upload only the `sdist`.

It would be nice to:
  - have an automated system which does a release whenever we push a relevant tag
  - build&upload wheels

**Comment by dralley** [comment]
Would you want to stay on Azure Pipelines or switch to Github Actions?

It looks like CPython is gradually switching https://bugs.python.org/issue39041

**Comment by antocuni** [comment]
I think it's fine (and probably preferable) to switch to Github Actions
