### ISSUE TITLE
TypeError: Cannot create a consistent method resolution (piconumpy build)

### ISSUE THREAD

**Issue by paugier** [hpyproject/hpy#224]
With hpy gitnode 7b45ce522c7bea265f50bb9d9cd04d651f84fa74:

```
pierre@gre ~/Dev/piconumpy bench-hpy-master $ python setup.py develop                                                                                                         
Traceback (most recent call last):
  File "/home/pierre/Dev/piconumpy/setup.py", line 4, in <module>
    setup(
  File "/home/pierre/.pyenv/versions/3.9.4/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/pierre/.pyenv/versions/3.9.4/lib/python3.9/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/pierre/.pyenv/versions/3.9.4/lib/python3.9/site-packages/setuptools/dist.py", line 455, in __init__
    _Distribution.__init__(self, {
  File "/home/pierre/.pyenv/versions/3.9.4/lib/python3.9/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/home/pierre/.pyenv/versions/3.9.4/lib/python3.9/site-packages/setuptools/dist.py", line 807, in finalize_options
    ep(self)
  File "/home/pierre/.pyenv/versions/3.9.4/lib/python3.9/site-packages/setuptools/dist.py", line 814, in _finalize_setup_keywords
    ep.load()(self, ep.name, value)
  File "/home/pierre/Dev/hpy/hpy/devel/__init__.py", line 115, in handle_hpy_ext_modules
    hpydevel.fix_distribution(dist)
  File "/home/pierre/Dev/hpy/hpy/devel/__init__.py", line 72, in fix_distribution
    class build_hpy_ext(build_hpy_ext_mixin, base_build_ext, object):
TypeError: Cannot create a consistent method resolution
order (MRO) for bases build_hpy_ext_mixin, build_hpy_ext, object
```

However, it's strange, it does not seem to be related to changes in hpy. I can come back to previous hpy commits and still I get that... 

Any ideas how to solve that ?

**Comment by antocuni** [comment]
FWIW, it works for me with `python 3.8.10` + `venv`. Maybe it's something specific to 3.9, but even that it weird because we **do** run tests on 3.9.
Does it happen for you also with python 3.8?

**Comment by hodgestar** [comment]
Note that **base_build_ext** appears to have evaluated to **build_hpy_ext**. See last line of:
```
TypeError: Cannot create a consistent method resolution
order (MRO) for bases build_hpy_ext_mixin, build_hpy_ext, object
```
Did `fix_distribution` somehow get called twice on the same `dist` object? Perhaps there are two copies of hpy installed somehow? Perhaps running under pdb and looking at which file the two `build_hpy_ext` are from will help figure out what happened.

**Comment by paugier** [comment]
I can reproduce with Python 3.8 (and in a new environment) so it does not seem 3.9 specific.

It seems to be related to installing hpy with `python setup.py develop` or `pip install -e .`.

To get rid of the problem, I need to `pip uninstall hpy.devel` and to manually remove `hpy.devel.egg-info` and `hpy.egg-info`.

Actually, I realize that `hpy.egg-info` is not created if I do `python setup.py develop` with hpy 2e6052b00e4151a88a21b786e79626f009274639. With hpy master, it is created and it seems to be related to the issue.

**Comment by hodgestar** [comment]
@paugier Ah, I have a guess about what might have happened. In 11f38b66 the name of the package was changed from `hpy.devel` to `hpy` and I suspect that switching between branches means that you now have both `hpy.devel` and `hpy` installed sometimes.

If the guess is correct, my suggestion would be to just avoid using HPy prior to 0.0.2 from now on if possible.

**Comment by paugier** [comment]
Good guess! Thanks!

My piconumpy branch is now updated (https://github.com/hpyproject/piconumpy/pull/3/commits/65d063ed9dc0b6f1746c357a52ad6cc43dab7f90).

BTW, it would be great if the corresponding PR (https://github.com/hpyproject/piconumpy/pull/3) could be merged. I thing there is nothing too bad in it and it just improves the situation.
