### ISSUE TITLE
Debug mode: check that returned value is a valid handle

### ISSUE THREAD

**Issue by steve-s** [hpyproject/hpy#258]
I noticed that CPython debug build fails on an assertion with code similar to this: 
```
static HPy g_impl(HPyContext *ctx, HPy self, HPy arg) {
   return arg;
}
```

in the current scheme of the debug mode where we check the handle validity in `HPy_Close` and watch for leaked handles, this is not detected. I think we need to add a check of the validity of return values into the `debug_ctx_CallRealFunctionFromTrampoline`.

**Comment by antocuni** [comment]
ah, maybe I know what's going on. The relevant code is this:
https://github.com/hpyproject/hpy/blob/c7d36aa3e08c32a49703b3afd22ac1bdc932f2aa/hpy/debug/src/debug_ctx_cpython.c#L87-L98

here we create the debug handle and then we `DHPy_close(arg)`, so in theory we get an `HPyDebugError` as soon as we try to do anything with it. But then we also `DHPy_close(return)`, which results in a double free in CPython.
In theory, `DHPy_close` could check that the handle is valid and complain early if you try to close a closed handle. But at the moment, we explicitly try to allow this use case:
https://github.com/hpyproject/hpy/blob/c7d36aa3e08c32a49703b3afd22ac1bdc932f2aa/hpy/debug/src/debug_handles.c#L92-L106

However, judging from this issue, it might be a bad idea and it might be just easier to let it crash early.

Bonus point if we manage to produce a better error for the specific case of return values (which is probably a very common error), something like `User function returned an invalid handle returned, maybe you forgot HPy_Dup?`

**Comment by steve-s** [comment]
Yes, I forgot about this "allow closing closed handle" exception, you're right.

> Bonus point if we manage to produce a better error for the specific case of return values (which is probably a very common error), something like User function returned an invalid handle returned, maybe you forgot HPy_Dup?

So AFAICS that would still require adding code for handling this into `debug_ctx_CallRealFunctionFromTrampoline`? I can take a look at implementing this. The removal of the "allow closing closed handle" exception can be a separate/next step. We can start with return values.

**Comment by steve-s** [comment]
Looking at the code again: 

the comment in `DHPy_close` says
```
        However, we leave the possibility to the user to install a custom hook 
        to be called when we detect an invalid handle. In this case, the 
        process does not abort and the execution tries to continue.
```
so one would think that if I do not set custom hook, it should still abort.

It seems to me that the code in `DHPy_close` is ignoring closed handles, because it assumes that `DHPy_unwrap` called in `debug_ctx_Close` would have aborted if there was no invalid handle hook.

https://github.com/hpyproject/hpy/blob/c7d36aa3e08c32a49703b3afd22ac1bdc932f2aa/hpy/debug/src/debug_ctx.c#L112

In the debug context trampoline we must avoid actually closing the universal handle, because the wrapped context did that for us, so we call only `DHPy_close`, right? But we do not call `DHPy_unwrap`, which means no check of validity.

**Comment by antocuni** [comment]
> Looking at the code again:
> 
> the comment in `DHPy_close` says
> 
> ```
>         However, we leave the possibility to the user to install a custom hook 
>         to be called when we detect an invalid handle. In this case, the 
>         process does not abort and the execution tries to continue.
> ```
> 
> so one would think that if I do not set custom hook, it should still abort.

yes, agreed. That's why I think we should comment out or remove the logic.
The basic idea is probably useful during porting, but until we have proper tests and support for it, it's useless.


> It seems to me that the code in `DHPy_close` is ignoring closed handles, because it assumes that `DHPy_unwrap` called in `debug_ctx_Close` would have aborted if there was no invalid handle hook.
> 
> https://github.com/hpyproject/hpy/blob/c7d36aa3e08c32a49703b3afd22ac1bdc932f2aa/hpy/debug/src/debug_ctx.c#L112-L117

yes, this is how we normally detect a duplicate `HPy_Close()`.

> In the debug context trampoline we must avoid actually closing the universal handle, because the wrapped context did that for us, so we call only `DHPy_close`, right? But we do not call `DHPy_unwrap`, which means no check of validity.

mostly correct, but note that it's more complicated than this. Look at this:
https://github.com/hpyproject/hpy/blob/c7d36aa3e08c32a49703b3afd22ac1bdc932f2aa/hpy/debug/src/debug_ctx_cpython.c#L87-L98

In the code above, we actually *do* check for validity of `result`, because `_dh2py` calls `DHPy_unwrap`.
The problem here is that `arg` and `result` are the same handle: at the moment of `_dh2py` the handle is valid, but then it's closed immediately after.
So, probably this is enough to detect it:
```c
        DHPy dh_result = f(dctx, dh_self, dh_arg);
        DHPy_close(dctx, dh_self);
        DHPy_close(dctx, dh_arg);
        a->result = _dh2py(dctx, dh_result);
        DHPy_close(dctx, dh_result);
```
