### ISSUE TITLE
Mechanism to distribute C source of some functions (perf JIT low level Python code using objects implemented with HPy)

### ISSUE THREAD

**Issue by paugier** [hpyproject/hpy#271]
The microbenchmarks described in https://github.com/hpyproject/hpy/issues/263 and the results obtained for GraalPython clearly show that to get good performance for low level numerical Python code using objects defined in HPy extensions, some JIT compilers need to be able to consider the C code of some functions (in particular used for indexing and looping), so that the hot loops written in low level Python can be optimized as one compilation unit and the tiny C functions used for indexing can be inlined.

To describe how this works now in GraalPython, I cite @steve-s (from answers in https://github.com/hpyproject/hpy/issues/263):

> GraalPython has a mode where it does not execute the actual native code, but LLVM bitcode inside the same JIT as the Python code.

> The drawbacks of the LLVM bitcode mode is that you need to install the extensions from source as we need to compile it to LLVM bitcode.

Remark: it seems to me that a reasonable approach in terms of performance would be to use the native compiled functions for most function calls and to use the LLVM bitcode mode only for some function calls in hot loops. 

The need to install the extension from source is of course a huge limitation because this is not the habit of the Python community (people install wheels or conda packages).

I'm raising here the issue of the lack of a mechanism to be able to distribute the C source of some functions that are likely to be used in hot loops (in particular indexing and `tp_iter`).

It seems to me that this issue could be addressed by the HPy project, since HPy is partly about writing and distributing extensions that interact well with Python implementations with JIT.

Aside question: from a theoretical point of view, can PyPy's JIT do something with the C code behind `arr[i]` (something better in terms of perf that compiling it and call the C function)?

**Comment by steve-s** [comment]
In case of GraalPython, the LLVM bitcode is embedded into the shared library and when GraalPython is loading such library, it prefers the bitcode execution over native execution. However, the shared library is regular usable shared library, albeit compiled with clang and with some flags that are better fit for bitcode execution, but not so good for native, e.g., with some optimizations disabled.

In theory, we could add a tag for such shared libraries and have them pre-built on PyPI. That would be awesome but it is, however, GraalPython specific and I don't think a discussion around this belongs to the HPy project.

Even if PyPy wanted to also JIT compile some intermediate C representation, the effort on standardizing that together with HPy would be huge and out of HPy scope I think. Moreover, I believe that in longer term future the aim should be that native extensions are used for use-cases where they are necessary (calling native libraries) and not for performance reasons, because implementations such as GraalPython or  PyPy can already run Python code with performance on par with or close to C code.

**Comment by paugier** [comment]
Thanks for the answers!

> In case of GraalPython, the LLVM bitcode is embedded into the shared library and when GraalPython is loading such library, it prefers the bitcode execution over native execution. However, the shared library is regular usable shared library, albeit compiled with clang and with some flags that are better fit for bitcode execution, but not so good for native, e.g., with some optimizations disabled.

It means that a universal extension compiled with GraalPython is not the same that the same extension compiled with CPython or PyPy. I didn't understand that I all. I though universal extensions were really "universal" :slightly_smiling_face: 

> Moreover, I believe that in longer term future the aim should be that native extensions are used for use-cases where they are necessary (calling native libraries) and not for performance reasons, because implementations such as GraalPython or PyPy can already run Python code with performance on par with or close to C code.

It seems to be the point of view shared by some developers of alternative Python implementations. I tend to disagree because pure Python lacks something like Numpy to be convenient to implement numerical kernels. In my opinion, pure Python without extension is not a good language to implement numerical code. That's why Cython has different kinds of arrays. And why Numba and Pythran are Python-Numpy compilers. All the scientific/numerical/data ecosystem relies on Numpy (and now other array extensions).

**Comment by mattip** [comment]
> And why Numba and Pythran are Python-Numpy compilers

To be clear: Numba and Pythran take the python expressions, including Numpy semantics, and __recompile__ them. As far as I know they do not re-use any of the NumPy C code. Numba has hand-written routines that compile down to LLVM IR code, that code is then optimized by LLVM backends. Pythran also rewrites Numpy/Python semantics into highly optimized C++ templated code, which is compiled ahead of time. Both of these solutions do what PyPy started doing in micronumpy: reimplement much of NumPy in a way that their "runtime" can optimize. The more we can convince the ecosystem to remain in high-level syntax (including the [array API](https://data-apis.org/array-api/latest/)), the easier it will be for Numba, Pythran, PyPy, and Graalpython to optimize the code.

**Comment by paugier** [comment]
> Both of these solutions do what PyPy started doing in micronumpy: reimplement much of NumPy in a way that their "runtime" can optimize.

Yes. As with NumPyPy. I thought HPy could be another approach: one extension implementation adapted for different Python implementations.

Maybe something like micronumpy should just be officially integrated in the standard library.

> The more we can convince the ecosystem to remain in high-level syntax (including the array API), the easier it will be for Numba, Pythran, PyPy, and Graalpython to optimize the code.

I'm a bit pessimistic that PyPy and GraalPython can strongly accelerate high level Numpy code compared to what is obtained with CPython (But of course it would be already great to be as fast as with CPython!) High level Numpy code is written such that the time spent by the Python interpreter is negligible compared to the time spent doing the work in Numpy functions. This is relatively efficient but in some cases the performance is limited by the need of temporary arrays. I suspect that it will be very difficult for PyPy and GraalPython to do better than what does CPython (i.e. just call the optimized Numpy functions and create the temporary objects).

Numba is much better to accelerate low level Numpy code than high level Numpy code. Only Pythran is remarkably good to really accelerate high level Numpy code (with less temporary arrays and XSIMD).

The preliminary results obtained with GraalPython and HPy/piconumpy are promising about potential acceleration of low level Numpy code.

Finally, there are algorithms that cannot be written with high level Numpy (or for which the low level implementation is much simpler / readable).

**Comment by steve-s** [comment]
> It means that a universal extension compiled with GraalPython is not the same that the same extension compiled with CPython or PyPy. I didn't understand that I all. I thought universal extensions were really "universal" slightly_smiling_face

Just to clarify this:

I think we will have to come up with something to improve the usability and clarity of this in GraalPython. This is purely about what compiler and compiler flags you use to compile your extension. If you override the defaults of GraalPython, it'll produce the same universal binary as any other Python with HPy support. Even with the defaults, the binary will still be universal, although not built with compiler flags that you may expect (although I think the difference would be mostly minor). You can also override the compiler/flags on PyPy and have it produce HPy universal extension with embedded bitcode the very same way.

Maybe we should have some explicit flag or mode that switches between the two. GraalPython can run regular universal binaries without bitcode and in some cases that may be even more desirable than bitcode execution even if you can build from sources.
