### ISSUE TITLE
Semantics of HPy_InPlacePower

### ISSUE THREAD

**Issue by antocuni** [hpyproject/hpy#28]
Currently, `HPy_InPlacePower` is just a proxy to `Py_InPlacePower`: however, its semantics is a bit weird. The official CPython docs say:

```
PyObject* PyNumber_Power(PyObject *o1, PyObject *o2, PyObject *o3)
Return value: New reference.

See the built-in function pow(). Returns NULL on failure. 
This is the equivalent of the Python expression pow(o1, o2, o3), 
where o3 is optional. If o3 is to be ignored, pass Py_None in its 
place (passing NULL for o3 would cause an illegal memory access).
```

However, the actual semantics is different: if an object implements `__ipow__`, the 3rd arg is always ignored. See e.g. commit 79077d1 and the relevant [PyPy commit](https://foss.heptapod.net/pypy/pypy/commit/b4f4537307ac80911b5305056a3a54d4c92b21f3).

I see two alternatives:

1. We simply mimic CPython but document the behavior
2. We "fix" the API, for example by making `HPy_InPlacePower` to accept only 2 arguments (because `__ipow__` accepts only one, after all). But in this case, should we keep this name or change it?

**Comment by timfel** [comment]
Did we check with CPython devs that this shouldn't be considered a bug in CPython or at least its documentation?

**Comment by hodgestar** [comment]
The response to the issue above suggests that this is a bug, but I don't see it being fixed any time soon, so I think we should just copy the behaviour -- we're not trying to fix every last niggle of the C API.
