### ISSUE TITLE
Numpy: port dtype and its static instances to HPy

### ISSUE THREAD

**Issue by steve-s** [hpyproject/hpy#298]
For this iteration I suggest to restrain from porting the dtype metatype. Porting `dtype` is currently blocked by metaclass support in HPy https://github.com/hpyproject/hpy/issues/296.

**Comment by mattip** [comment]
Metatypes are supported. Is this part of the NumPy port?

**Comment by fangerer** [comment]
I think we can close this issue. Yes, metaclasses are now supported in HPy and yes, we basically already did the migration.
It would be nice if we could open issues in https://github.com/hpyproject/numpy-hpy .

**Comment by mattip** [comment]
I wonder who the owner is for [that fork](https://github.com/hpyproject/numpy-hpy)? Perhaps they could open up issues. Maybe @rlamy?

**Comment by rlamy** [comment]
@mattip I enabled issues there. AFAICT, every hpyproject owner could have done it.

**Comment by mattip** [comment]
I am a [hpyproject member](https://github.com/orgs/hpyproject/people), so I could neither see who is a maintainer nor change the settings.
