### ISSUE TITLE
Why use `HPyContext *` rather than `HPyContext` as the first parameter.

### ISSUE THREAD

**Issue by markshannon** [hpyproject/hpy#352]
This is more a question than an issue.
Why use `HPyContext *` rather than `HPyContext`?

I'm not suggesting passing the context struct by value, but hiding the pointer:
```C
typedef struct _ctx {
   struct HPyContextStruct *ptr;
} HPyContext;
```
It seems more in keeping with the "make everything opaque" nature of HPy.

**Comment by antocuni** [comment]
Having a completly opaque context was the original plan, and indeed originally it was called `HPyContext`, not `HPyContext *`, see https://github.com/hpyproject/hpy/pull/182 (although it was just a typedef a not opaque as-in-your-example).

We switched to `HPyContex *` to support `ctx->h_None`, `ctx->h_True`, etc.
There is also an open design issue about whether `ctx->h_None` & co. are a good idea: https://github.com/hpyproject/hpy/pull/182

**Comment by hodgestar** [comment]
The structure of the `HPyContext` is the ABI, so in some sense it is always exposed. However, this is a core part of the API from a user perspective, so we would like to get it as right as possible.

**Comment by markshannon** [comment]
I understand that for the portable ABI, the context struct has to be a big table of pointers and such. But does that make sense for the API? 

> We switched to HPyContex * to support ctx->h_None, ctx->h_True, etc

According to https://github.com/hpyproject/hpy/blob/master/hpy/tools/autogen/public_api.h `h_None`, etc are independent of the context. I think is reasonable to expect `None`, and some other values, to be process wide.

**Comment by markshannon** [comment]
Anyway, it seems like this is duplicating discussion already happening elsewhere.

**Comment by fangerer** [comment]
Just for reference, at least one part of the discussion happened in issue #226 .

**Comment by antocuni** [comment]
Thank you @fangerer . I wanted to mention #226 in my original answer, but I did copy&paste wrong. I'll edit the answer so that future readers will be less confused :)
