### ISSUE TITLE
Clarify encoding used for C strings in the API.

### ISSUE THREAD

**Issue by markshannon** [hpyproject/hpy#355]
It is not clear what encoding is used for C strings in the API. Are they ASCII, latin-1, or utf-8?

Either make this clear in the docs (maybe it is, but my cursory inspection didn't find it), or better still in the API itself.
A simple typedef would suffice.
```C
typedef const char *Utf8String;
```
This would also make it clearer what is text data, and what is just bytes.

In `HPyBytes_FromStringAndSize(HPyContext *ctx, const char *v, HPy_ssize_t len)`, `v` is just an array of bytes,
but in `HPyImport_ImportModule(HPyContext *ctx, const char *name)` `name` is a name.
The name gives a clue, but the encoding is hidden.
`HPyImport_ImportModule(HPyContext *ctx, Utf8String name)` is much clearer.

**Comment by timfel** [comment]
I agree, I think [utf8everywhere](https://utf8everywhere.org) is the right approach and we should make that clear in the name

**Comment by fangerer** [comment]
We decided in [today's dev call](https://github.com/hpyproject/hpy/wiki/dev-call-20221201) that we will just do that.
