### ISSUE TITLE
Add two argument versions of common HPyDef_ macros

### ISSUE THREAD

**Issue by hodgestar** [hpyproject/hpy#359]
It would be nice to have to repeat oneself less when defining slots and methods. E.g. instead of writing

```HPyDef_SLOT(Point_traverse, Point_traverse_impl, HPy_tp_traverse)```

it would be nice to write just:

```HPyDef_SLOT(Point_traverse, HPy_tp_traverse)``` and have the implementation be Point_traverse_impl by convention.

We can then keep the three argument versions for corner cases, or maybe even just get rid of them eventually? If one really needs a different name one can use a `#define`? This last paragraph is up for discussion.

**Comment by antocuni** [comment]
sorry, I see it only now. I'd vote for killing they three argument versions: in the common case you use the short version, and if you need more control over the names you just write an `HPyDef` manually.

**Comment by fangerer** [comment]
Afaik, this issue is resolved.
