### ISSUE TITLE
Consider let build fail when hpy-abi=universal and `Py*` symbols are discovered

### ISSUE THREAD

**Issue by timfel** [hpyproject/hpy#366]
This could happen when the stub loader is created, since the `.so` exists at that point. It would ensure that people don't accidentally build hpy universal binaries that only work because our implementations currently have cpyext (or are CPython)

**Comment by mattip** [comment]
Another option is to set up compilation so that any use of `Python.h` will fail. This could be done by setting the include macro and creating a "fake" `Python.h`. Maybe both methods are needed to actually prove the binary is truly universal.

**Comment by mattip** [comment]
I think this can be closed now that #371 is merged. Please reopen if I misunderstood.
