### ISSUE TITLE
Improve the API/implementation for HPyCapsule_Destructor

### ISSUE THREAD

**Issue by antocuni** [hpyproject/hpy#377]
this is best explained by this comment:
https://github.com/hpyproject/hpy/pull/308#issuecomment-1322131574

**Comment by fangerer** [comment]
I just did a quick grep in the `top4000` packages for `PyCapsule_GetDestructor` and didn't find a single usage. So, let's kill it!

**Comment by antocuni** [comment]
> I just did a quick grep in the `top4000` packages for `PyCapsule_GetDestructor` and didn't find a single usage. So, let's kill it!

yes, kill it!
