### ISSUE TITLE
Test that we run `make autogen`

### ISSUE THREAD

**Issue by antocuni** [hpyproject/hpy#39]
I open this as an issue to avoid forgetting.

We should add a test which checks that if we run `make autogen`, we get the same output as the files which are committed in the repo. This ensures:

  1. that we didn't forget to call it after changing `public_api.h` and/or `autogen.py` itself

  2. that we didn't modify the autogenerated code by hand

**Comment by thedrow** [comment]
Isn't this already done?

**Comment by antocuni** [comment]
you are correct, this was fixed by #65
