### ISSUE TITLE
Multi-phase module initialization

### ISSUE THREAD

**Issue by fangerer** [hpyproject/hpy#397]
IIRC from the discussions, supporting multi-phase module initialization is a precondition for #286 .
Further, as we agreed in [January 2023's dev call](https://github.com/hpyproject/hpy/wiki/dev-call-20230112), we will drop support for single-phase module init.

**Comment by mattip** [comment]
Closing as complete. Please reopen if I misunderstood.

**Comment by fangerer** [comment]
> Closing as complete.

👍
