### ISSUE TITLE
Move the project to hpy/hpy

### ISSUE THREAD

**Issue by mattip** [hpyproject/hpy#44]
At the last community call we talked about changing the group name to hpy. It seems that org name is taken. Any other thoughts? hpy-dev ?

**Comment by hodgestar** [comment]
`hpy` would have been nice, but I'm not feeling particularly excited by moving to `hpy-*`.

**Comment by timobure** [comment]
`hpy` would have been the best. But if it is taken, I would be okay continuing with the current `pyhandle` name. I actually like it

**Comment by rlamy** [comment]
We've now moved to hpyproject/hpy, so I guess this is resolved.
