### ISSUE TITLE
Add an example or test that uses HPy_mod_execute

### ISSUE THREAD

**Issue by mattip** [hpyproject/hpy#443]
In porting hpy-0.9 to PyPy, I could [not find](https://github.com/search?q=org%3Ahpyproject%20HPy_mod_execute&type=code) an example of using the `HPy_mod_execute` slot. It is mentioned in the [documentation](https://docs.hpyproject.org/en/latest/quickstart.html?highlight=HPy_mod_execute#hpy-quickstart)
> The Python interpreter will create the module for us from the `HPyModuleDef` specification. Additional initialization can be done in the `HPy_mod_execute` slot

but there is no example of using that slot.

**Comment by fangerer** [comment]
Not sure if we should do it in the quickstart example (since it is not really necessary in this example). But we can, ofc, link to one example. The incremental porting example shows it: https://docs.hpyproject.org/en/latest/porting-example/index.html#id1

**Comment by steve-s** [comment]
There are tests of this and little bit of documentation:
https://github.com/hpyproject/hpy/blob/master/test/test_hpymodule.py
