### ISSUE TITLE
HPyErr_Format missing

### ISSUE THREAD

**Issue by mattip** [hpyproject/hpy#463]
It would be nice to have HPyErr_Format with a signature like [`PyErr_Format`](https://github.com/python/cpython/blob/4b3cb082da82da744f5db0b7315aa80558c51557/Include/pyerrors.h#L180)
```
PyErr_Format(PyObject *exception, const char *format, ...);
```

**Comment by fangerer** [comment]
It is there: https://github.com/hpyproject/hpy/blob/a5c70cd1c19304bb2a164ab3dd69ab46b1ed542a/hpy/devel/include/hpy/runtime/format.h#L16

**Comment by mattip** [comment]
Ahh, thanks, missed that. Then it should be used in the NumPy port [here](https://github.com/hpyproject/numpy-hpy/blob/23f4a1898d37af3dd3525144eb800c64abfdb495/numpy/core/src/multiarray/mapping.c#L1417), I will add it to my PR.

**Comment by fangerer** [comment]
Yes, there may be many locations where it should be used. We introduced it after we started migrating NumPy. I personally always added a `TODO` and kept the full C API call in a comment and I thought I later fixed all those. Others may not have marked those locations. So, whenever you find one, feel free to migrate and open a PR.
