### ISSUE TITLE
Is keeping 2.7 compatibility for `hpy/devel/__init__.py` still relevant?

### ISSUE THREAD

**Issue by Sachaa-Thanasius** [hpyproject/hpy#477]
Note: Not a bug or a feature, more of a general question.

Context: This note at the top of `hpy/devel/__init__.py` —
```py
# NOTE: this file is also imported by PyPy tests, so it must be compatible
# with both Python 2.7 and Python 3.x
```

I'm not that familiar with PyPy, but I know `pathlib` in CPython is only available in the standard library for 3.x. If PyPy's in a similar boat, and considering that library is being used seemingly without issue in this file's code, is the note above still relevant?

**Comment by mattip** [comment]
There is a [backport of pathlib for Python2](https://pypi.org/project/pathlib/).

**Comment by Sachaa-Thanasius** [comment]
Ah, the note’s still relevant then, and pathlib is accounted for. Got it.
