### ISSUE TITLE
Have different set of functions with different availability and stability warranties

### ISSUE THREAD

**Issue by vstinner** [hpyproject/hpy#6]
It's going to be hard to ensure that all functions are available on all Python versions of all Python implementations. Dummy example: some Python 3 functions of the C API are not available in the Python 2 API, and some functions introduced in Python 3.8 are not available in Python 3.6.

The first use case would be to compile a C extension to target Python version X.Y or newer. Newer functions would not be available.

We might have have experimental APIs. For example, should we expose an API to access CPython 3.8 vector call?

Does someone know a similar concept in mature popular APIs like the Windows API, Qt, glib or something else?

**Comment by windelbouwman** [comment]
In windows there is the concept of API Sets: https://docs.microsoft.com/en-us/windows/win32/apiindex/windows-apisets

This is very handy concept. You could group functions. Assign maturity to certain sets. If there is a new version of an API set, you can write an adapter for the old API set mapping onto the new API set, if this might be required.

In general I like the idea of grouping functions. We could even create a system which can query which API's are supported by a python implementation :).

**Comment by antocuni** [comment]
API sets are an interesting concept, however I am not 100% sure they applies to our use case. If I understand it correctly, in API sets the name of the function in the source code is always the same, but in DLLs they have the version number hardcoded; so for Python it means that a call to `PyLong_FromLong()` will becomes e.g. `PyLong_FromLong__cp37` or something like that.
This could be useful if we want a certain version of CPython to support many different versions of the API, but I don't think this is what we want, don't we?

A much simpler solution to achieve what victor suggests is to rely on `#define`, something like that:
```C
#define HPY_TARGET_36
#include <HPy.h>
```
this way, `HPy.h` would expose only the APIs present in version 3.6, and with enough effort the resulting .so could be loaded both in 3.6 and 3.7.

**Comment by windelbouwman** [comment]
The exact method of assigning a version to an API is maybe not directly usable. The idea I was more interested in was the idea to split up the API into several API / protocols. So, in that sense, there is not one python API, it is a group of API sets. This has the benefit that API sets can be deprecated as a whole, and also the stability of whole groups of functions can be guaranteed.

Also note that the python protocols such as the dict and attribute protocol could be nicely mapped into an API set.

For example:

```
API_set PyDict [maturity=stable, version=1.0] {
   fn get_item(HPy object, HPy key) -> HPy;
   fn set_item(HPy object, HPy key, HPy value);
}

API_set PyAttribute [maturity=stable, version=1.0] {
  fn get_attr();
  fn set_attr();
  fn del_attr();
}

API_set PyInt [maturity=draft] {
   fn add(int a, int b) -> HPy;
}
```

**Comment by antocuni** [comment]
>The exact method of assigning a version to an API is maybe not directly usable. The idea I was more interested in was the idea to split up the API into several API / protocols. 

I am still not sure to see the practical advantage of this: do you foresee a future in which certain Python implementations can implement different subsets of the API, and each extension module needs to take that into account?

Do you want to be able to select different versions of the API at compile time or runtime?
```
API_set PyDict [maturity=stable, version=1.0] {
  fn get_item(HPy object, HPy key) -> HPy;
  fn set_item(HPy object, HPy key, HPy value);
}
```
this looks nice, but it is also very impractical to do it in C, isn't it?

**Comment by vstinner** [comment]
In HPy.h, it expects something like:

```
#if HPY_TARGET >= 37
EXPORT(int) HPy_function_of_API_version_37(...);
#endif
```

and so get a compilation error on:

```
#define HPY_TARGET 36
#include <HPy.h>
int main() {
   return HPy_function_of_API_version_37(); /* doesn't exist in API 3.6 */
}
```

**Comment by vstinner** [comment]
CPython already has something like that called "Py_LIMITED_API". Example of Include/abstract.h (in CPython master branch):

```
#if !defined(Py_LIMITED_API) || Py_LIMITED_API+0 >= 0x03090000
/* Call a callable Python object without any arguments */
PyAPI_FUNC(PyObject *) PyObject_CallNoArgs(PyObject *func);
#endif
```

**Comment by windelbouwman** [comment]
> I am still not sure to see the practical advantage of this: do you foresee a future in which certain Python implementations can implement different subsets of the API, and each extension module needs to take that into account?

I think the argument to do this, is in another area. The python API as a whole will probably never be stable, since it is rather large. How many functions does it contain? I do not know, I estimate in the order of about ~100-~1000. An API with this many functions is hard to stabilize. Splitting the API into API sets might enable us to mark some sets as final and never to be changed again. Users can then choose to rely only on stabilized API sets, or live on the edge, and use everything which is available.

> this looks nice, but it is also very impractical to do it in C, isn't it?

:) This is by no means valid C, it's more rust-like, but once you use rust, it is no fun working in C.. The idea was more to indicate the idea.

A proper C variant would maybe look like this:
```c
// For returning either a succesful value, or an exception.
typedef struct {
  enum { ok = 0, err = 1 }
  union {
    HPy* ok_value;
    HPy* err_value;
  }
} HPyResult;

// Api for items, version 1.
// Naming scheme: <prefix>_<ApiSet>_<version>_<function>
HPyResult* HPy_ItemProcotol_v1_GetItem(Hpy* obj, HPy* key);
HPyResult* HPy_ItemProcotol_v1_SetItem(Hpy* obj, HPy* key, HPy* value);
```

**Comment by windelbouwman** [comment]
Btw, maybe this is off-topic, but how about extensions written in rust, C# or java? Would these extensions use the same API?

**Comment by antocuni** [comment]
> Btw, maybe this is off-topic, but how about extensions written in rust, C# or java? Would these extensions use the same API?

I think the initial focus will be on a C API, because it is the most used and it's ubiquitous. I suppose that rust should easily be able to write a nice wrapper on top of it, which could include things like automatically closing the handles. C++ could do something like that as well.

Java it is a different thing and I have no clue how an API for writing CPython extensions in Java would look like 😅. But in any case, I don't think this should be the focus of this project

**Comment by hodgestar** [comment]
I think is now covered by issue #374 and pull request #356, so closing this.
