### ISSUE TITLE
Custom object types

### ISSUE THREAD

**Issue by arigo** [hpyproject/hpy#9]
We need to think about custom object types with a structure declared in C.  We don't want to repeat CPython's mistake about explicit destructors everywhere containing Py_DECREF() and a hack on top of that for reference cycles.  There must be a better solution, which would also allow an implementation like PyPy's which doesn't need to walk most dead objects at all.

I would suggest to declare local variables and arguments of type "POD" (Python Object Descriptor, or handles), and use a different "PORef" type for fields in objects (Python Object Reference).

`PORef_Store(PORef *pref, POD o);     /* '*pref = o;' with conversion */`
`PORef_Clear(PORef *pref);      /* '*pref = NULL;' */`
`PORef_Load(PORef *pref);      /* returns a new POD, which must be closed */`

Then it would be mandatory to write an equivalent of tp_traverse to list all PORefs in an object.  The main difference between POD and PORef is that a POD must be closed when no longer in use, but not a PORef.  A PORef is alive if and only if it is stored in an object, the tp_traverse of this object is called, and that function lists the PORef.

Of course the implementation of both POD and PORef are `PyObject *` under the hood on CPython.  On PyPy a POD could be an integer index in some global list, but a PORef could be a real pointer which might be internally changed during tp_traverse.

**Comment by arigo** [comment]
Note also the safety benefits on CPython.  In CPython you can read a `PyObject *` from a heap object and keep it in some local variable, borrowed---hoping that no-one else will remove the original reference from the heap object, and referencing free memory if someone does.  You can no longer do that here; instead, you need to use `PORef_Load()`, which is doing a `Py_INCREF()` internally.

Wouldn't that create a lot of pairs Py_INCREF() immediately followed by Py_DECREF()?  Yes, but nowadays we can leave it to gcc and clang to remove the most obvious of them.  I checked that the following code compiles to no assembly at all:

```
void do_stuff(PyObject *p)
{
    if (!p->refcount++) __builtin_unreachable();   /* INCREF */
    if (!--p->refcount) free_me(p);                /* DECREF */
}
```

The `__builtin_unreachable()` makes the compiler assume that the refcount before INCREF couldn't have been zero.  So it knows that the DECREF branch will not hit zero, either.

**Comment by antocuni** [comment]
after an IRC chat with arigo, we designed the following idea (which uses the HPy naming convention instead of the proposed POD one). All the names are subjected to be changed.
One of the goal is to be able to store real GC pointer inside the custom type structs: this has the big advantage that we can use a fast GC to allocate objects instead of relying on a non-movable but slow `malloc()`.

So, custom C structs which wants to store other HPy objects can declare fields of type `HPyField`. You are not allowed to store an `HPyField` into a local variable (because the GC might move the pointed object). Instead, you can `HPy_Load` a field and turn it into a proper handle.

Moreover, if you have a `HPy` handle but you want to access the actual fields of the concrete C struct, you can `HPy_Cast` it: the returned pointer is guaranteed to be valid until the handle is closed.

The following is a "complete" example containing all the ideas above:
```C
typedef struct {
    HPyObject_HEAD
    double x;
    double y;
} HPy_Point;

typedef struct {
    HPyObject_HEAD
    HPyField a;
    HPyField b;
} HPy_Rectangle;

/* ... */

HPy new_rect(HPy p1, HPy p2) {
    // HPy_New always initialize the whole object to 0. We can also have
    // HPy_NewUninitialized if we don't want to pay the penalty
    HPy_Rectangle *rect;
    HPy rect_handle = HPy_New(HPy_Rectangle, &HPy_RectangleType, &rect);

    // HPy_Store does a write barrier on PyPy, and DECREF the old rect->a on
    // CPython if needed
    HPy_Store(&rect->a, p1);
    HPy_Store(&rect->b, p2);
    return rect_handle;
}

double calc_diagonal(HPy rect_handle) {
    // rect is valid until rect_handle is closed. on PyPy we pin the object, and
    // we unpin it when we close the handle
    HPy_Rectangle *rect = HPy_Cast(HPy_Rectangle, rect_handle);

    // HPy_Load reads a field and turn it into a handle
    HPy p1_handle = HPy_Load(rect->a); // p1 is a handle which must be closed
    HPy_Point *p1 = HPy_Cast(HPy_Point, p1_handle);

    // for C99 compilers, we can also provide a macro which declares p2 and
    // p2_handle automatically and does the equivalent of the two lines above
    HPY_LOAD(HPy_Point, p2, rect->b);
    
    HPy p2_handle = HPy_Load(rect->a, HPy_Point);
    HPy_Point *p2 = HPy_Cast(HPy_Point, p2_handle);

    double diag = sqrt(p1->x - p2->x /* etc. etc. */);

    // close all the handles
    HPy_Close(p1_handle);
    HPy_Close(p2_handle);

    return diag;
}


/* random notes:
   we want:
   HPy_Cast to convert from HPy handles to concrete structs: no type checks
   HPy_TypeCheck to check that a HPy handle is of a certain type
   HPy_TryCast which combines the above two
   HPY_TRY_LOAD which uses HPy_TryCast instead of HPy_Cast
*/
```

**Comment by hodgestar** [comment]
Discussion from Leysin sprint: It feels like we currently have too many concepts involved here -- an `HPy` handle, an `HPyField` and an `HPyPoint *`. This generates complex life cycle handling and many lines of code that we would like to avoid.

However, we currently have no idea how to do better. :)

We should look at how the JVM handles this.
